config/routes.rb
Rails.application.routes.draw do
  get 'mynotes/index'
  get 'notes/about' => 'notes#about'
  get 'notes/contact' => 'notes#contact'
  get 'notes/other_projects' => 'notes#other_projects'
  devise_for :users, controllers: { registrations: 'registrationes' }
  root 'notes#index'
  resources :notes do
    resources :comments
  end
  resources :mynotes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @note = Note.find(params[:note_id])
    @comment = @note.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to note_path(@note)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/mynotes_controller.rb
class MynotesController < ApplicationController
  def index
    @user = current_user
    @mynotes = Note.where(user_id: current_user)
  end
  def show
    @user = current_user
    @note = Note.find(params[:id])
    @mynotes = Note.where(user_id: current_user)
  end
  def edit
    @user = current_user
    @note = Note.find(params[:id])
  end
  def update
    @note = Note.find(params[:id])
    @note.update(note_params)
    redirect_to mynote_path(@note)
  end
  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to mynotes_path
  end

  private
  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # before_action :authenticate_user!
  def index
    @user = current_user
    @notes = Note.all
    @notesuser = Note.where(user_id: current_user)
  end
  def new
    @user = current_user
    @note = current_user.notes.build
  end
  def update
    @note = Note.find(params[:id])
    @note.update(note_params)
    redirect_to mynote_path(@note)
  end
  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  def show
    @note = Note.find(params[:id])
    @user = User.find(@note.user_id)
    @notes = Note.all
  end
  def about

  end

  private
  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/controllers/registrationes_controller.rb
class RegistrationesController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = 'Note Tracker'
    if title.empty?
      base_title
    elsif user_signed_in?
      title + " | " + current_user.first_name
    else
      title + " | " + base_title
    end

  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mynotes_helper.rb
module MynotesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/registrationes_helper.rb
module RegistrationesHelper
end

app/views/layouts/_comment.html.haml
-if @note.comments.count < 1
-else
  %h4
    Comments
-@note.comments.each do |comment|
  %p
    =comment.body
    %br
    <em>
    ="-#{User.find(comment.user_id).first_name}"
    = time_ago_in_words(comment.created_at)
    ago
    </em>

= form_for [@note, @note.comments.build] do |f|
  %p
    =f.label 'comment'
  -if @note.comments.count < 1
    %p
      =f.text_area :body, placeholder: "Be the first to comment!", class: "input-box"
  -else
    %p
      =f.text_area :body, placeholder: "Add your comment here. Keep it civil!", class: "input-box"
  %p
    =f.submit 'Post', class: 'submit-btn'

app/views/layouts/_comment_form.html.haml
= form_for [@note, @note.comments.build] do |f|
  %p
    =f.label 'comment'
  -if @note.comments.count < 1
    %p
      =f.text_area :body, placeholder: "Be the first to comment!", class: "input-box"
  -else
    %p
      =f.text_area :body, placeholder: "Add your comment here. Keep it civil!", class: "input-box"
  %p
    =f.submit 'Post', class: 'submit-btn'

app/views/layouts/_comments.html.haml
-if @note.comments.count < 1
-else
  %h4
    Comments
-@note.comments.each do |comment|
  %p
    =comment.body
    %br
    <em>
    ="-#{User.find(comment.user_id).first_name}"
    = time_ago_in_words(comment.created_at)
    ago
    </em>

app/views/layouts/_cruds.html.haml
%button.cruds
  = link_to "edit note", edit_mynote_path, class: "link"
%button.cruds
  = link_to "delete", mynote_path, method: :delete, class: "link"
%button.cruds
  = link_to "back", :back, class: "link"

app/views/layouts/_footer.html.haml
%footer
  %ul
    %li
      =link_to "About", notes_about_path
    %li
      =link_to "Contact", notes_contact_path
    %li
      =link_to "Other Projects", notes_other_projects_path

app/views/layouts/_form.html.haml
= form_for @note do |f|
  %p
    header
    %br
    = f.text_field :title, class: "input-box"
  %p
    note
    %br
    = f.text_area :body, class: "input-area"
    -if current_page?(new_note_path)
      = f.submit 'Post', class: "submit-btn"
    -elsif current_page?(edit_mynote_path)
      = f.submit 'Edit', class: "submit-btn"

    = link_to "Back", :back, class: "submit-btn link-to-btn"

app/views/layouts/_mynotes.html.haml
-@mynotes.each do |note|
  =link_to mynote_path(note),class: "note-tag" do
    .the-note
      %h3.center
        =note.title
      %p
        =truncate(note.body, length: 45)
      %p
        =time_ago_in_words(note.created_at)
        ago

app/views/layouts/_nav.html.haml
%nav
  =link_to notes_path do
    .header
      =image_tag("note-4.png",class: 'logo')
      .title Note Tracker
      .drop-down A Rails app by spenser tingey

  -if user_signed_in?

    = link_to destroy_user_session_path, method: :delete do
      .taz
        Sign Out
    = link_to new_note_path do
      .taz{:class => ("active" if current_page?(new_note_path))}
        New Note
    = link_to mynotes_path do
      .taz{:class => ("active" if current_page?(mynotes_path))}
        My Notes
    = link_to notes_path do
      .taz{:class => ("active" if current_page?(notes_path) || current_page?(root_path))}
        All Notes
  -else
    = link_to new_user_session_path do
      .taz{:class => ("active" if current_page?(new_user_session_path))}
        Log in
    = link_to new_user_registration_path do
      .taz{:class => ("active" if current_page?(new_user_registration_path))}
        Sign up
    = link_to notes_path do
      .taz{:class => ("active" if current_page?(notes_path) || current_page?(root_path))}
        All Notes

app/views/layouts/_notes.html.haml
-@notes.each do |note|
  -if current_user == nil
    =link_to note_path(note), class: "note-tag" do
      .the-note
        %h3.center
          =note.title
        %p
          =truncate(note.body, length: 45)
        %p
          =time_ago_in_words(note.created_at)
          ago by
          =User.find(note.user_id).first_name
  -elsif current_user.id == note.user_id
    =link_to mynote_path(note), class: "note-tag" do
      .the-note
        %h3.center
          =note.title
        %p
          =truncate(note.body, length: 45)
        %p
          =time_ago_in_words(note.created_at)
          ago by
          =User.find(note.user_id).first_name
  -else
    =link_to note_path(note), class: "note-tag" do
      .the-note
        %h3.center
          =note.title
        %p
          =truncate(note.body, length: 45)
        %p
          =time_ago_in_words(note.created_at)
          ago by
          =User.find(note.user_id).first_name

app/views/layouts/_showstuff.html.haml
%h3.center
  =@note.title
%p
  =@note.body

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/png"  href="http://simpleicon.com/wp-content/uploads/note-4.png"/>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    <div class = 'login-alerts'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/mynotes/edit.html.haml
=provide(:title, 'Edit Note')
.container2
  %h2
    edit note for
    =@user.first_name
  =render 'layouts/form'

app/views/mynotes/index.html.haml
=provide(:title, "My Notes")
-# %h2 Test Header
.header-div
  My Notes
.container1
  =render 'layouts/mynotes'

app/views/mynotes/show.html.haml
.header-div
  My Notes
.container1
  =render 'layouts/mynotes'
.container2
  %h2.center
    My Note
  = render 'layouts/showstuff'
  = render 'layouts/cruds'
  = render 'layouts/comments'
  = render 'layouts/comment_form'

app/views/notes/about.html.haml
=provide(:title, 'About')
%h2
  About:
%p
  My name is Spenser and I like to make web apps

app/views/notes/contact.html.haml
=provide(:title, 'Contact')
%h2
  Contact:
%p
  spenser.tingey@gmail.com

app/views/notes/index.html.haml
=provide(:title, "All Notes")
.header-div
  All Notes
.container1
  =render 'layouts/notes'

app/views/notes/new.html.haml
=provide(:title, "New Note")
.container2
  %h2
    create new note for
    =@user.first_name
  =render 'layouts/form'

app/views/notes/other_projects.html.haml
=provide(:title, 'Other Projects')
%h2
  Other projects:
%ul
  %li
    %a{href: "https://sheltered-wildwood-53056.herokuapp.com/", class: 'links', target:"_blank"} Star Wars rails API project

app/views/notes/show.html.haml
.header-div
  All Notes
.container1
  =render 'layouts/notes'
.container2
  %h2.center
    Note by
    =@user.first_name
    =render 'layouts/showstuff'


  -if user_signed_in?
    =render 'layouts/comments'
    =render 'layouts/comment_form'
  -else
    =render 'layouts/comments'
    =link_to "Sign in", new_user_session_path
    to comment!